"""
Ex 100 - Create a module called coin.py that has the
built in functions increase (), decrease (), double ()
and half (). Also make a program that imports these
modules and use some of these functions


A) create an additional function called currency () that can display the values ​​as a formatted monetary value.
B) Inform whether the values ​​informed by the functions will be formatted by the currency function or not using a parameter
C) create a function called summary(), which shows on the screen some information generated by the functions we already have in the module created so far
D) create a package called utilities that has two internal modules called coin and data. transfer the functions used so far for them. And keep it all working
E) create a function called read_money() that is able to function as the input() function, but with data validation to accept only values ​​that are monetary.

"""
from utilities import coin, data

p = data.read_money('Enter a Value: R$')
coin.summary(p, 20, 10)

input('Enter to Exit')
